name: Build and deploy site to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v3
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install node dependencies
      run: pnpm install
    - name: create env file
      run: |
        cd apps/jflb-live
        touch .env
        echo VITE_APP_SUPABASE_URL=${{secrets.SUPABASE_URL}} >> .env
        echo VITE_APP_SUPABASE_KEY=${{secrets.SUPABASE_KEY}} >> .env
    # - name: Lint
      # run: pnpm lint
    - name: Build
      run: pnpm build
    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/www/dist
        cname: app.nicolasjouanno.com
